name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest

        with:
          filename: github-metrics.svg

          token: ${{ secrets.METRICS_TOKEN }}

          user: AarjanAdhikari

          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kathmandu

          config_display: large

          config_padding: 0

          # Black & White Theme
          config_theme: github-dark
          config_twemoji: no
          config_octicon: yes

          # Languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          # Calendar
          plugin_isocalendar: yes

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C

          # Stars
          plugin_stars: yes

          # Follow-up
          plugin_followup: yes

          # Lines
          plugin_lines: yes
